### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by perlpunk** [DrHyde/perl-modules-Data-Compare#15]
Which license does this module have?

https://metacpan.org/source/DCANTRELL/Data-Compare-1.27/META.yml:

    license: open_source

https://metacpan.org/source/DCANTRELL/Data-Compare-1.27/META.json

    "license" : [
       "artistic_1",
       "gpl_2"
    ],

We stumbled upon this while maintaining the perl modules repository in openSUSE.

**Comment by DrHyde** [comment]
Makefile.PL says `license => ["artistic_1", "gpl_2"]` so it looks like you've found a bug in ExtUtils::MakeMaker, which is what translates that into META.{yml,json}. Thanks for reporting it, I'll pass it on.

Also note that it is spelled out more clearly in a human-readable form here: https://metacpan.org/pod/Data::Compare#COPYRIGHT-and-LICENCE

**Comment by DrHyde** [comment]
Apparently "This is expected behavior. Meta 1.4 (yml) can't express dual-licenses,
so it summarizes it to open source or not."

**Comment by haarg** [comment]
For reference: https://metacpan.org/pod/CPAN::Meta::History::Meta_1_4#license
