### ISSUE TITLE
Incorrect result when hash contains undef

### ISSUE THREAD

**Issue by Duoxilian** [DrHyde/perl-modules-Data-Compare#21]
When comparing data structures which contain a hash which has a field that holds an undefined value as the first parameter, Data::Compare returns true even if the structures do not match:

```
<DB 1> p Compare({a=>{b=>undef}}, {a=>{c=>12}})
1
```

The two data structures must otherwise match.

**Comment by DrHyde** [comment]
That's a bit of an embarrassing bug! Thanks for letting me know, I'll take a look.

**Comment by DrHyde** [comment]
Should be fixed in 90cd9960. Once the CI has had a change to chew over it I'll push out a new release.

**Comment by Duoxilian** [comment]
Thanks for fixing this so quickly. It was amazing how long this bug took to surface.

Thanks also for this nice utility.

**Comment by DrHyde** [comment]
Version 1.28 is on its way to the CPAN now.
